### ISSUE TITLE
Handle missing icon in app

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-modelstudio#134]
Problems with app icon: For hmdb, the icon is missing in left menu - but displayed nicely in visualization?

![Screenshot 2022-10-14 at 15 41 26](https://user-images.githubusercontent.com/482228/195861567-f4a27be0-f6ad-4aa5-b6d4-e591aad8c550.png)

**Comment by reisfmb** [comment]
Only happening with some icons in Firefox...
